# Generated by Django 4.1 on 2022-08-15 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_user_mother_likes_userprofile_cordinats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 9, 11, 41, 999197, tzinfo=datetime.timezone.utc)),
        ),
    ]
