# Generated by Django 4.1 on 2022-08-15 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_user_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 14, 11, 24, 505234, tzinfo=datetime.timezone.utc)),
        ),
    ]
