# Generated by Django 4.1 on 2022-08-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mothers',
            old_name='likes',
            new_name='mom_id',
        ),
        migrations.RemoveField(
            model_name='mothers',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mothers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mothers',
            name='name',
        ),
        migrations.AddField(
            model_name='mothers',
            name='mom_like_id_user',
            field=models.PositiveIntegerField(default=0, verbose_name='лайки'),
        ),
    ]
